-- favorites: 음식 단위 즐겨찾기 저장 테이블
create table if not exists public.favorites (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  mn text not null,
  st text not null default '',
  img text,
  pr text,
  good text,
  rev text,
  cat text,
  unique (mn, st)
);

-- 보안 잠금(RLS) 켜기
alter table public.favorites enable row level security;

-- 프로토타입용: 누구나(anon) 읽기/쓰기 허용 정책
drop policy if exists "favorites_all_anon" on public.favorites;
create policy "favorites_all_anon"
  on public.favorites for all
  to anon
  using (true) with check (true);

-- 권한 부여
grant select, insert, update, delete on table public.favorites to anon;
